-- Resumes Table
CREATE TABLE resumes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name VARCHAR(255) NOT NULL,
    file_type VARCHAR(100) NOT NULL,
    file_size BIGINT NOT NULL,
    storage_path VARCHAR(500) NOT NULL,
    extracted_text TEXT,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by VARCHAR(100),
    updated_by VARCHAR(100)
);

-- Resume Analysis Table
CREATE TABLE resume_analysis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resume_id BIGINT NOT NULL REFERENCES resumes(id) ON DELETE CASCADE,
    ats_score INTEGER NOT NULL,
    formatting_score INTEGER NOT NULL,
    keywords_score INTEGER NOT NULL,
    experience_score INTEGER NOT NULL,
    education_score INTEGER NOT NULL,
    overall_feedback TEXT,
    candidate_name VARCHAR(150),
    experience_level VARCHAR(50),
    top_skills TEXT,        -- Comma-separated list
    strengths TEXT,         -- Comma-separated list or JSON-structured
    missing_skills TEXT,    -- JSON-structured text
    ai_suggestions TEXT,    -- JSON-structured text
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by VARCHAR(100),
    updated_by VARCHAR(100)
);

-- Interview Questions Table
CREATE TABLE interview_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resume_analysis_id BIGINT NOT NULL REFERENCES resume_analysis(id) ON DELETE CASCADE,
    question TEXT NOT NULL,
    type VARCHAR(50) NOT NULL, -- Behavioral, Technical, Situational
    tip TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by VARCHAR(100),
    updated_by VARCHAR(100)
);

-- Career Recommendations Table
CREATE TABLE career_recommendations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resume_analysis_id BIGINT NOT NULL REFERENCES resume_analysis(id) ON DELETE CASCADE,
    roadmap TEXT NOT NULL,      -- JSON-structured roadmap
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by VARCHAR(100),
    updated_by VARCHAR(100)
);
